"""Schema and FK fanout statistics for relational database collections.

This module compares three schema sources:

* RelBench precomputed schema graph statistics.
* DBInfer/MTBench-style datasets with ``metadata.yaml``.
* Synthetic databases generated by ``syn_data``.

FK edges are treated as schema-level join support, not as causal edges.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

try:
    import yaml
except ImportError:  # pragma: no cover - PyYAML is listed in requirements.
    yaml = None


GRAPH_METRIC_COLUMNS = [
    "source_group",
    "dataset_id",
    "dataset_path",
    "num_tables",
    "num_edges",
    "edge_density",
    "is_dag",
    "dag_depth",
    "root_count",
    "root_ratio",
    "leaf_count",
    "leaf_ratio",
    "max_degree",
    "max_indegree",
    "max_outdegree",
    "hub_count",
    "hub_tables",
    "role_counts",
]

EDGE_FANOUT_COLUMNS = [
    "source_group",
    "dataset_id",
    "parent_table",
    "child_table",
    "parent_col",
    "child_col",
    "parent_rows",
    "child_rows",
    "referenced_parent_keys",
    "mean_fanout",
    "median_fanout",
    "p90_fanout",
    "p95_fanout",
    "max_fanout",
    "zero_child_parent_ratio",
    "orphan_fk_ratio",
    "fanout_status",
]


@dataclass(frozen=True)
class TableInfo:
    """Table metadata and optional on-disk data path."""

    name: str
    primary_key: Optional[str] = None
    row_count: Optional[int] = None
    role: Optional[str] = None
    data_path: Optional[Path] = None
    data_format: Optional[str] = None
    columns: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class EdgeInfo:
    """Schema-level FK support edge from parent table to child table."""

    parent_table: str
    child_table: str
    parent_col: Optional[str] = None
    child_col: Optional[str] = None


@dataclass
class SourceStats:
    """Per-source metric rows."""

    per_db_rows: List[Dict[str, Any]] = field(default_factory=list)
    edge_rows: List[Dict[str, Any]] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)


def analyze_sources(
    relbench_stats_json: Optional[Path] = None,
    existing_root: Optional[Path] = None,
    synthetic_root: Optional[Path] = None,
    output_dir: Optional[Path] = None,
    skip_fanout: bool = False,
    max_dbs: Optional[int] = None,
) -> Dict[str, Any]:
    """Collect statistics and write report artifacts."""
    stats = SourceStats()

    if relbench_stats_json is not None:
        stats = _merge_stats(stats, collect_relbench_stats(relbench_stats_json, max_dbs=max_dbs))
    if existing_root is not None:
        stats = _merge_stats(
            stats,
            collect_dbinfer_stats(existing_root, skip_fanout=skip_fanout, max_dbs=max_dbs),
        )
    if synthetic_root is not None:
        stats = _merge_stats(
            stats,
            collect_synthetic_stats(synthetic_root, skip_fanout=skip_fanout, max_dbs=max_dbs),
        )

    if not stats.per_db_rows:
        raise RuntimeError("No database schema statistics were collected.")

    output = Path(output_dir or "syn_data/outputs/analysis/schema_stats")
    output.mkdir(parents=True, exist_ok=True)

    per_db_df = _frame_with_columns(stats.per_db_rows, GRAPH_METRIC_COLUMNS)
    edge_df = _frame_with_columns(stats.edge_rows, EDGE_FANOUT_COLUMNS)
    aggregate_df = build_aggregate_comparison(per_db_df)

    per_db_path = output / "per_db_metrics.csv"
    edge_path = output / "edge_fanout.csv"
    aggregate_path = output / "aggregate_comparison.csv"
    summary_path = output / "summary.md"
    report_path = output / "report.json"

    per_db_df.to_csv(per_db_path, index=False)
    edge_df.to_csv(edge_path, index=False)
    aggregate_df.to_csv(aggregate_path, index=False)

    summary_text = build_summary_markdown(per_db_df, edge_df, aggregate_df, stats.warnings)
    summary_path.write_text(summary_text, encoding="utf-8")

    report = {
        "outputs": {
            "summary": str(summary_path),
            "per_db_metrics": str(per_db_path),
            "edge_fanout": str(edge_path),
            "aggregate_comparison": str(aggregate_path),
            "report": str(report_path),
        },
        "num_databases": int(len(per_db_df)),
        "num_edges": int(len(edge_df)),
        "source_groups": sorted(str(group) for group in per_db_df["source_group"].dropna().unique()),
        "warnings": stats.warnings,
    }
    report_path.write_text(json.dumps(_json_ready(report), indent=2, ensure_ascii=False), encoding="utf-8")
    return report


def collect_relbench_stats(path: Path, max_dbs: Optional[int] = None) -> SourceStats:
    """Read precomputed RelBench schema graph statistics."""
    stats = SourceStats()
    source = Path(path)
    if not source.exists():
        stats.warnings.append(f"RelBench stats JSON not found: {source}")
        return stats

    payload = json.loads(source.read_text(encoding="utf-8"))
    datasets = payload if isinstance(payload, list) else list(payload.values())
    if max_dbs is not None:
        datasets = datasets[: max(0, int(max_dbs))]

    for dataset in datasets:
        dataset_id = str(dataset.get("dataset") or dataset.get("dataset_id") or "relbench_unknown")
        nodes_payload = dataset.get("nodes", [])
        edges_payload = dataset.get("edges", [])
        tables = {
            str(node["table"]): TableInfo(
                name=str(node["table"]),
                primary_key=_optional_str(node.get("pkey_col")),
                row_count=_optional_int(node.get("rows")),
            )
            for node in nodes_payload
            if "table" in node
        }
        edges = [
            EdgeInfo(
                parent_table=str(edge.get("parent_table") or edge.get("source_table")),
                child_table=str(edge.get("child_table") or edge.get("target_table")),
                parent_col=_optional_str(edge.get("parent_pkey_col") or edge.get("parent_col")),
                child_col=_optional_str(edge.get("fkey_col") or edge.get("child_col")),
            )
            for edge in edges_payload
            if edge.get("parent_table") or edge.get("source_table")
        ]
        stats.per_db_rows.append(
            graph_metrics_row(
                source_group="relbench",
                dataset_id=dataset_id,
                dataset_path=str(source),
                tables=tables,
                edges=edges,
            )
        )
        for edge_payload, edge in zip(edges_payload, edges):
            stats.edge_rows.append(_relbench_edge_row(dataset_id, edge_payload, edge))
    return stats


def collect_synthetic_stats(
    root: Path,
    skip_fanout: bool = False,
    max_dbs: Optional[int] = None,
) -> SourceStats:
    """Scan ``syn_data`` generated database directories."""
    stats = SourceStats()
    base = Path(root)
    db_dirs = _discover_synthetic_dirs(base)
    if max_dbs is not None:
        db_dirs = db_dirs[: max(0, int(max_dbs))]
    if not db_dirs:
        stats.warnings.append(f"No synthetic schema directories found under: {base}")
        return stats

    for db_dir in db_dirs:
        try:
            schema_path = db_dir / "schema" / "schema.json"
            schema = json.loads(schema_path.read_text(encoding="utf-8"))
            tables = _synthetic_tables(schema, db_dir)
            edges = _synthetic_edges(schema)
            dataset_id = str(schema.get("schema_id") or db_dir.name)
            stats.per_db_rows.append(
                graph_metrics_row(
                    source_group="synthetic",
                    dataset_id=dataset_id,
                    dataset_path=str(db_dir),
                    tables=tables,
                    edges=edges,
                )
            )
            stats.edge_rows.extend(
                fanout_rows_for_edges(
                    source_group="synthetic",
                    dataset_id=dataset_id,
                    tables=tables,
                    edges=edges,
                    skip_fanout=skip_fanout,
                )
            )
        except Exception as exc:
            stats.warnings.append(f"Failed to read synthetic DB {db_dir}: {exc}")
    return stats


def collect_dbinfer_stats(
    root: Path,
    skip_fanout: bool = False,
    max_dbs: Optional[int] = None,
) -> SourceStats:
    """Scan DBInfer/MTBench-style directories containing ``metadata.yaml``."""
    stats = SourceStats()
    base = Path(root)
    dataset_dirs = _discover_metadata_dirs(base)
    if max_dbs is not None:
        dataset_dirs = dataset_dirs[: max(0, int(max_dbs))]
    if not dataset_dirs:
        stats.warnings.append(f"No metadata.yaml datasets found under: {base}")
        return stats

    for dataset_dir in dataset_dirs:
        try:
            metadata = _read_yaml(dataset_dir / "metadata.yaml")
            if not isinstance(metadata, Mapping) or "tables" not in metadata:
                stats.warnings.append(f"Skipping metadata without tables: {dataset_dir / 'metadata.yaml'}")
                continue
            dataset_id = str(metadata.get("dataset_name") or dataset_dir.name)
            tables = _dbinfer_tables(metadata, dataset_dir)
            edges = _dbinfer_edges(metadata)
            stats.per_db_rows.append(
                graph_metrics_row(
                    source_group="existing",
                    dataset_id=dataset_id,
                    dataset_path=str(dataset_dir),
                    tables=tables,
                    edges=edges,
                )
            )
            stats.edge_rows.extend(
                fanout_rows_for_edges(
                    source_group="existing",
                    dataset_id=dataset_id,
                    tables=tables,
                    edges=edges,
                    skip_fanout=skip_fanout,
                )
            )
        except Exception as exc:
            stats.warnings.append(f"Failed to read existing DB {dataset_dir}: {exc}")
    return stats


def graph_metrics_row(
    source_group: str,
    dataset_id: str,
    dataset_path: str,
    tables: Mapping[str, TableInfo],
    edges: Sequence[EdgeInfo],
) -> Dict[str, Any]:
    """Compute graph-level schema metrics."""
    table_names = sorted(tables)
    indegree = {name: 0 for name in table_names}
    outdegree = {name: 0 for name in table_names}
    adjacency: Dict[str, List[str]] = {name: [] for name in table_names}

    valid_edges = []
    for edge in edges:
        if edge.parent_table not in indegree or edge.child_table not in indegree:
            continue
        indegree[edge.child_table] += 1
        outdegree[edge.parent_table] += 1
        adjacency[edge.parent_table].append(edge.child_table)
        valid_edges.append(edge)

    num_tables = len(table_names)
    num_edges = len(valid_edges)
    denominator = num_tables * (num_tables - 1) / 2
    edge_density = float(num_edges / denominator) if denominator > 0 else 0.0

    root_tables = [name for name in table_names if indegree[name] == 0]
    leaf_tables = [name for name in table_names if outdegree[name] == 0]
    is_dag, dag_depth = _dag_depth(table_names, adjacency, indegree)

    degrees = {name: indegree[name] + outdegree[name] for name in table_names}
    degree_values = np.asarray(list(degrees.values()), dtype=float)
    degree_mean = float(degree_values.mean()) if degree_values.size else 0.0
    degree_std = float(degree_values.std()) if degree_values.size else 0.0
    hub_threshold = max(3.0, degree_mean + degree_std)
    hub_tables = [name for name in table_names if degrees[name] >= hub_threshold]

    role_counts = Counter(info.role for info in tables.values() if info.role)

    return {
        "source_group": source_group,
        "dataset_id": dataset_id,
        "dataset_path": dataset_path,
        "num_tables": num_tables,
        "num_edges": num_edges,
        "edge_density": edge_density,
        "is_dag": bool(is_dag),
        "dag_depth": dag_depth,
        "root_count": len(root_tables),
        "root_ratio": _safe_ratio(len(root_tables), num_tables),
        "leaf_count": len(leaf_tables),
        "leaf_ratio": _safe_ratio(len(leaf_tables), num_tables),
        "max_degree": int(max(degrees.values())) if degrees else 0,
        "max_indegree": int(max(indegree.values())) if indegree else 0,
        "max_outdegree": int(max(outdegree.values())) if outdegree else 0,
        "hub_count": len(hub_tables),
        "hub_tables": json.dumps(hub_tables[:10], ensure_ascii=False),
        "role_counts": json.dumps(dict(role_counts), ensure_ascii=False),
    }


def fanout_rows_for_edges(
    source_group: str,
    dataset_id: str,
    tables: Mapping[str, TableInfo],
    edges: Sequence[EdgeInfo],
    skip_fanout: bool = False,
) -> List[Dict[str, Any]]:
    """Compute one fanout row per FK edge."""
    cache: Dict[str, Optional[pd.DataFrame]] = {}
    rows = []
    for edge in edges:
        rows.append(
            _fanout_row(
                source_group=source_group,
                dataset_id=dataset_id,
                edge=edge,
                tables=tables,
                table_cache=cache,
                skip_fanout=skip_fanout,
            )
        )
    return rows


def build_aggregate_comparison(per_db_df: pd.DataFrame) -> pd.DataFrame:
    """Summarize graph metrics by source group."""
    metrics = [
        "num_tables",
        "num_edges",
        "edge_density",
        "dag_depth",
        "root_ratio",
        "leaf_ratio",
        "max_degree",
        "max_indegree",
        "max_outdegree",
        "hub_count",
    ]
    rows: List[Dict[str, Any]] = []
    if per_db_df.empty:
        return pd.DataFrame(columns=["source_group", "metric", "count", "mean", "std", "min", "p25", "median", "p75", "max"])

    for source_group, group in per_db_df.groupby("source_group", dropna=False):
        for metric in metrics:
            values = pd.to_numeric(group.get(metric), errors="coerce").dropna()
            rows.append(
                {
                    "source_group": source_group,
                    "metric": metric,
                    "count": int(values.count()),
                    "mean": float(values.mean()) if not values.empty else None,
                    "std": float(values.std(ddof=0)) if not values.empty else None,
                    "min": float(values.min()) if not values.empty else None,
                    "p25": float(values.quantile(0.25)) if not values.empty else None,
                    "median": float(values.median()) if not values.empty else None,
                    "p75": float(values.quantile(0.75)) if not values.empty else None,
                    "max": float(values.max()) if not values.empty else None,
                }
            )
    return pd.DataFrame(rows)


def build_summary_markdown(
    per_db_df: pd.DataFrame,
    edge_df: pd.DataFrame,
    aggregate_df: pd.DataFrame,
    warnings: Sequence[str],
) -> str:
    """Build a compact human-readable Markdown report."""
    lines = [
        "# Schema/FK Statistics Report",
        "",
        "FK edges are interpreted as schema-level join support, not as causal edges.",
        "",
        "## Source Overview",
        "",
    ]

    overview_rows = []
    for source_group, group in per_db_df.groupby("source_group", dropna=False):
        overview_rows.append(
            {
                "source_group": source_group,
                "databases": len(group),
                "avg_tables": _fmt_num(pd.to_numeric(group["num_tables"], errors="coerce").mean()),
                "avg_edges": _fmt_num(pd.to_numeric(group["num_edges"], errors="coerce").mean()),
                "avg_density": _fmt_num(pd.to_numeric(group["edge_density"], errors="coerce").mean()),
                "avg_depth": _fmt_num(pd.to_numeric(group["dag_depth"], errors="coerce").mean()),
            }
        )
    lines.extend(_markdown_table(overview_rows))

    lines.extend(["", "## Aggregate Comparison", ""])
    compact_aggregate = aggregate_df[
        aggregate_df["metric"].isin(["num_tables", "num_edges", "edge_density", "dag_depth", "root_ratio", "leaf_ratio"])
    ].copy()
    compact_rows = []
    for _, row in compact_aggregate.iterrows():
        compact_rows.append(
            {
                "source_group": row["source_group"],
                "metric": row["metric"],
                "count": int(row["count"]),
                "mean": _fmt_num(row["mean"]),
                "median": _fmt_num(row["median"]),
                "min": _fmt_num(row["min"]),
                "max": _fmt_num(row["max"]),
            }
        )
    lines.extend(_markdown_table(compact_rows))

    relbench_df = per_db_df[per_db_df["source_group"] == "relbench"]
    if not relbench_df.empty:
        lines.extend(["", "## RelBench Databases", ""])
        relbench_rows = []
        for _, row in relbench_df.sort_values("dataset_id").iterrows():
            relbench_rows.append(
                {
                    "dataset": row["dataset_id"],
                    "tables": int(row["num_tables"]),
                    "edges": int(row["num_edges"]),
                    "density": _fmt_num(row["edge_density"]),
                    "depth": "cycle/null" if not bool(row["is_dag"]) else _fmt_num(row["dag_depth"]),
                    "roots": int(row["root_count"]),
                    "leaves": int(row["leaf_count"]),
                    "max_degree": int(row["max_degree"]),
                }
            )
        lines.extend(_markdown_table(relbench_rows))

    lines.extend(["", "## Difference Notes", ""])
    lines.extend(_difference_notes(per_db_df, "synthetic", "relbench"))
    lines.extend(_difference_notes(per_db_df, "existing", "relbench"))

    lines.extend(["", "## Exceptions", ""])
    cycle_rows = per_db_df[per_db_df["is_dag"] == False]  # noqa: E712
    no_fk_rows = per_db_df[pd.to_numeric(per_db_df["num_edges"], errors="coerce").fillna(0) == 0]
    missing_fanout = edge_df[
        ~edge_df["fanout_status"].isin(["ok", "from_relbench_stats"])
    ] if not edge_df.empty else pd.DataFrame(columns=edge_df.columns)
    orphan_high = edge_df[
        pd.to_numeric(edge_df["orphan_fk_ratio"], errors="coerce").fillna(0.0) > 0.05
    ] if not edge_df.empty else pd.DataFrame(columns=edge_df.columns)

    lines.append(f"- Cycle/non-DAG databases: {len(cycle_rows)}")
    lines.append(f"- Databases without FK edges: {len(no_fk_rows)}")
    lines.append(f"- Edges with missing/uncomputed fanout: {len(missing_fanout)}")
    lines.append(f"- Edges with orphan_fk_ratio > 0.05: {len(orphan_high)}")

    if not missing_fanout.empty:
        lines.extend(["", "### Fanout Missing Preview", ""])
        preview = missing_fanout.head(10)[["source_group", "dataset_id", "parent_table", "child_table", "fanout_status"]]
        lines.extend(_markdown_table(preview.to_dict("records")))
    if warnings:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {warning}" for warning in warnings[:50])
    lines.append("")
    return "\n".join(lines)


def _fanout_row(
    source_group: str,
    dataset_id: str,
    edge: EdgeInfo,
    tables: Mapping[str, TableInfo],
    table_cache: Dict[str, Optional[pd.DataFrame]],
    skip_fanout: bool,
) -> Dict[str, Any]:
    base = {
        "source_group": source_group,
        "dataset_id": dataset_id,
        "parent_table": edge.parent_table,
        "child_table": edge.child_table,
        "parent_col": edge.parent_col,
        "child_col": edge.child_col,
        "parent_rows": _table_rows(tables.get(edge.parent_table)),
        "child_rows": _table_rows(tables.get(edge.child_table)),
        "referenced_parent_keys": None,
        "mean_fanout": None,
        "median_fanout": None,
        "p90_fanout": None,
        "p95_fanout": None,
        "max_fanout": None,
        "zero_child_parent_ratio": None,
        "orphan_fk_ratio": None,
        "fanout_status": "not_computed",
    }
    if skip_fanout:
        base["fanout_status"] = "skipped"
        return base
    if not edge.parent_col or not edge.child_col:
        base["fanout_status"] = "missing_fk_columns"
        return base

    parent_df = _load_table(edge.parent_table, tables, table_cache)
    child_df = _load_table(edge.child_table, tables, table_cache)
    if parent_df is None or child_df is None:
        base["fanout_status"] = "missing_table"
        return base
    base["parent_rows"] = len(parent_df)
    base["child_rows"] = len(child_df)
    if edge.parent_col not in parent_df.columns or edge.child_col not in child_df.columns:
        base["fanout_status"] = "missing_column"
        return base

    parent_keys = _hashable_series(parent_df[edge.parent_col].dropna()).drop_duplicates()
    child_keys = _hashable_series(child_df[edge.child_col].dropna())
    if parent_keys.empty:
        base["fanout_status"] = "empty_parent_keys"
        base["orphan_fk_ratio"] = 1.0 if len(child_keys) else 0.0
        return base

    parent_key_set = set(parent_keys.tolist())
    valid_child_keys = child_keys[child_keys.isin(parent_key_set)]
    invalid_child_count = int(len(child_keys) - len(valid_child_keys))
    counts = valid_child_keys.value_counts()
    fanout_values = counts.to_numpy(dtype=float)
    referenced_parent_keys = int(len(counts))

    base.update(
        {
            "referenced_parent_keys": referenced_parent_keys,
            "mean_fanout": _quantile_or_zero(fanout_values, "mean"),
            "median_fanout": _quantile_or_zero(fanout_values, 0.50),
            "p90_fanout": _quantile_or_zero(fanout_values, 0.90),
            "p95_fanout": _quantile_or_zero(fanout_values, 0.95),
            "max_fanout": _quantile_or_zero(fanout_values, "max"),
            "zero_child_parent_ratio": _safe_ratio(len(parent_keys) - referenced_parent_keys, len(parent_keys)),
            "orphan_fk_ratio": _safe_ratio(invalid_child_count, len(child_keys)),
            "fanout_status": "ok",
        }
    )
    return base


def _relbench_edge_row(dataset_id: str, edge_payload: Mapping[str, Any], edge: EdgeInfo) -> Dict[str, Any]:
    child_nonnull = _optional_float(edge_payload.get("child_nonnull_fkeys"))
    missing_parent_keys = _optional_float(edge_payload.get("missing_parent_keys")) or 0.0
    parent_distinct = _optional_float(edge_payload.get("parent_distinct_keys") or edge_payload.get("parent_rows"))
    child_distinct = _optional_float(edge_payload.get("child_distinct_fkeys"))
    referenced = min(child_distinct or 0.0, parent_distinct or child_distinct or 0.0)
    return {
        "source_group": "relbench",
        "dataset_id": dataset_id,
        "parent_table": edge.parent_table,
        "child_table": edge.child_table,
        "parent_col": edge.parent_col,
        "child_col": edge.child_col,
        "parent_rows": _optional_int(edge_payload.get("parent_rows")),
        "child_rows": _optional_int(edge_payload.get("child_rows")),
        "referenced_parent_keys": int(referenced) if referenced is not None else None,
        "mean_fanout": _optional_float(edge_payload.get("fanout_parent_mean")),
        "median_fanout": _optional_float(edge_payload.get("fanout_parent_p50")),
        "p90_fanout": None,
        "p95_fanout": _optional_float(edge_payload.get("fanout_parent_p95")),
        "max_fanout": _optional_float(edge_payload.get("fanout_parent_max")),
        "zero_child_parent_ratio": (
            _safe_ratio((parent_distinct or 0.0) - referenced, parent_distinct)
            if parent_distinct
            else None
        ),
        "orphan_fk_ratio": _safe_ratio(missing_parent_keys, child_nonnull) if child_nonnull else 0.0,
        "fanout_status": "from_relbench_stats",
    }


def _synthetic_tables(schema: Mapping[str, Any], db_dir: Path) -> Dict[str, TableInfo]:
    nodes = schema.get("nodes", {})
    tables: Dict[str, TableInfo] = {}
    for table_id, node in nodes.items():
        table_path = db_dir / "tables" / f"{table_id}.parquet"
        tables[str(table_id)] = TableInfo(
            name=str(table_id),
            primary_key=_optional_str(node.get("primary_key")),
            row_count=_optional_int(node.get("num_rows")),
            role=_optional_str(node.get("role")),
            data_path=table_path if table_path.exists() else None,
            data_format="parquet" if table_path.exists() else None,
            columns=[str(col.get("name")) for col in node.get("columns", []) if isinstance(col, Mapping) and col.get("name")],
        )
    return tables


def _synthetic_edges(schema: Mapping[str, Any]) -> List[EdgeInfo]:
    edges = []
    for fk in schema.get("foreign_keys", []):
        edges.append(
            EdgeInfo(
                parent_table=str(fk.get("parent_table")),
                child_table=str(fk.get("child_table")),
                parent_col=_optional_str(fk.get("parent_col")),
                child_col=_optional_str(fk.get("child_col")),
            )
        )
    return edges


def _dbinfer_tables(metadata: Mapping[str, Any], dataset_dir: Path) -> Dict[str, TableInfo]:
    tables = {}
    for table in metadata.get("tables", []):
        table_name = str(table.get("name"))
        columns = [str(col.get("name")) for col in table.get("columns", []) if col.get("name")]
        primary_key = None
        row_count = None
        for col in table.get("columns", []):
            if str(col.get("dtype")) == "primary_key":
                primary_key = _optional_str(col.get("name"))
                row_count = _optional_int(col.get("capacity"))
                break
        source = table.get("source")
        data_path = (dataset_dir / str(source)).resolve() if source else None
        data_format = _optional_str(table.get("format"))
        tables[table_name] = TableInfo(
            name=table_name,
            primary_key=primary_key,
            row_count=row_count,
            data_path=data_path if data_path and data_path.exists() else None,
            data_format=data_format,
            columns=columns,
        )
    return tables


def _dbinfer_edges(metadata: Mapping[str, Any]) -> List[EdgeInfo]:
    edges = []
    for table in metadata.get("tables", []):
        child_table = str(table.get("name"))
        for col in table.get("columns", []):
            if str(col.get("dtype")) != "foreign_key":
                continue
            link_to = col.get("link_to")
            if not link_to or "." not in str(link_to):
                continue
            parent_table, parent_col = str(link_to).split(".", 1)
            edges.append(
                EdgeInfo(
                    parent_table=parent_table,
                    child_table=child_table,
                    parent_col=parent_col,
                    child_col=_optional_str(col.get("name")),
                )
            )
    return edges


def _discover_synthetic_dirs(root: Path) -> List[Path]:
    if (root / "schema" / "schema.json").exists():
        return [root]
    if not root.exists():
        return []
    return sorted(path.parent.parent for path in root.glob("*/schema/schema.json"))


def _discover_metadata_dirs(root: Path) -> List[Path]:
    if (root / "metadata.yaml").exists():
        return [root]
    if not root.exists():
        return []
    dirs = []
    for metadata_path in sorted(root.rglob("metadata.yaml")):
        try:
            payload = _read_yaml(metadata_path)
        except Exception:
            continue
        if isinstance(payload, Mapping) and "tables" in payload:
            dirs.append(metadata_path.parent)
    return dirs


def _read_yaml(path: Path) -> Any:
    if yaml is None:
        raise ImportError("PyYAML is required to read metadata.yaml files.")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _load_table(
    table_name: str,
    tables: Mapping[str, TableInfo],
    cache: Dict[str, Optional[pd.DataFrame]],
) -> Optional[pd.DataFrame]:
    if table_name in cache:
        return cache[table_name]
    info = tables.get(table_name)
    if info is None or info.data_path is None:
        cache[table_name] = None
        return None
    try:
        fmt = (info.data_format or info.data_path.suffix.lstrip(".")).lower()
        if fmt == "parquet" or info.data_path.suffix.lower() == ".parquet":
            df = pd.read_parquet(info.data_path)
        elif fmt == "csv" or info.data_path.suffix.lower() == ".csv":
            df = pd.read_csv(info.data_path)
        elif fmt == "numpy" or info.data_path.suffix.lower() in {".npy", ".npz"}:
            df = _read_numpy_table(info)
        else:
            cache[table_name] = None
            return None
    except Exception:
        cache[table_name] = None
        return None
    cache[table_name] = df
    return df


def _read_numpy_table(info: TableInfo) -> Optional[pd.DataFrame]:
    if info.data_path is None:
        return None
    loaded = np.load(info.data_path, allow_pickle=True)
    if isinstance(loaded, np.lib.npyio.NpzFile):
        key = "data" if "data" in loaded.files else loaded.files[0]
        arr = loaded[key]
    else:
        arr = loaded
    if getattr(arr.dtype, "names", None):
        return pd.DataFrame.from_records(arr)
    if arr.ndim == 2 and info.columns and len(info.columns) == arr.shape[1]:
        return pd.DataFrame(arr, columns=info.columns)
    return None


def _dag_depth(
    table_names: Sequence[str],
    adjacency: Mapping[str, Sequence[str]],
    indegree: Mapping[str, int],
) -> Tuple[bool, Optional[int]]:
    indegree_work = dict(indegree)
    distances = {name: 0 for name in table_names}
    queue = deque(name for name in table_names if indegree_work.get(name, 0) == 0)
    visited = 0
    while queue:
        node = queue.popleft()
        visited += 1
        for child in adjacency.get(node, []):
            distances[child] = max(distances[child], distances[node] + 1)
            indegree_work[child] -= 1
            if indegree_work[child] == 0:
                queue.append(child)
    if visited != len(table_names):
        return False, None
    return True, max(distances.values()) if distances else 0


def _hashable_series(series: pd.Series) -> pd.Series:
    return series.map(_hashable_value)


def _hashable_value(value: Any) -> Any:
    if isinstance(value, np.ndarray):
        return tuple(_hashable_value(item) for item in value.tolist())
    if isinstance(value, list):
        return tuple(_hashable_value(item) for item in value)
    if isinstance(value, tuple):
        return tuple(_hashable_value(item) for item in value)
    if isinstance(value, set):
        return tuple(sorted(_hashable_value(item) for item in value))
    if isinstance(value, dict):
        return tuple(sorted((key, _hashable_value(val)) for key, val in value.items()))
    if isinstance(value, np.generic):
        return value.item()
    return value


def _quantile_or_zero(values: np.ndarray, quantile: Any) -> float:
    if values.size == 0:
        return 0.0
    if quantile == "mean":
        return float(np.mean(values))
    if quantile == "max":
        return float(np.max(values))
    return float(np.quantile(values, float(quantile)))


def _safe_ratio(numerator: Any, denominator: Any) -> Optional[float]:
    try:
        denom = float(denominator)
    except (TypeError, ValueError):
        return None
    if denom == 0.0 or math.isnan(denom):
        return 0.0
    return float(numerator) / denom


def _table_rows(info: Optional[TableInfo]) -> Optional[int]:
    return None if info is None else info.row_count


def _optional_str(value: Any) -> Optional[str]:
    if value is None:
        return None
    return str(value)


def _optional_int(value: Any) -> Optional[int]:
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
        return int(value)
    except (TypeError, ValueError):
        return None


def _optional_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(result):
        return None
    return result


def _frame_with_columns(rows: Sequence[Mapping[str, Any]], columns: Sequence[str]) -> pd.DataFrame:
    df = pd.DataFrame(list(rows))
    for col in columns:
        if col not in df.columns:
            df[col] = None
    return df[list(columns)]


def _merge_stats(left: SourceStats, right: SourceStats) -> SourceStats:
    left.per_db_rows.extend(right.per_db_rows)
    left.edge_rows.extend(right.edge_rows)
    left.warnings.extend(right.warnings)
    return left


def _difference_notes(per_db_df: pd.DataFrame, source_group: str, baseline_group: str) -> List[str]:
    if source_group not in set(per_db_df["source_group"]) or baseline_group not in set(per_db_df["source_group"]):
        return [f"- {source_group} vs {baseline_group}: insufficient data."]
    notes = []
    for metric in ["num_tables", "num_edges", "edge_density", "dag_depth", "root_ratio", "leaf_ratio"]:
        source_values = pd.to_numeric(
            per_db_df.loc[per_db_df["source_group"] == source_group, metric],
            errors="coerce",
        ).dropna()
        baseline_values = pd.to_numeric(
            per_db_df.loc[per_db_df["source_group"] == baseline_group, metric],
            errors="coerce",
        ).dropna()
        if source_values.empty or baseline_values.empty:
            continue
        source_mean = float(source_values.mean())
        baseline_mean = float(baseline_values.mean())
        direction = "higher" if source_mean > baseline_mean else "lower"
        notes.append(
            f"- {source_group} {metric}: {_fmt_num(source_mean)} vs "
            f"{baseline_group} {_fmt_num(baseline_mean)} ({direction})."
        )
    return notes or [f"- {source_group} vs {baseline_group}: no numeric metrics available."]


def _markdown_table(rows: Sequence[Mapping[str, Any]]) -> List[str]:
    if not rows:
        return ["_No rows._"]
    columns = list(rows[0].keys())
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_markdown_cell(row.get(col)) for col in columns) + " |")
    return lines


def _markdown_cell(value: Any) -> str:
    if value is None:
        return ""
    return str(value).replace("|", "\\|").replace("\n", " ")


def _fmt_num(value: Any) -> str:
    if value is None:
        return ""
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    if math.isnan(number):
        return ""
    if abs(number - round(number)) < 1e-9:
        return str(int(round(number)))
    return f"{number:.3f}"


def _json_ready(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(k): _json_ready(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_ready(item) for item in value]
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        if math.isnan(float(value)):
            return None
        return float(value)
    if isinstance(value, np.ndarray):
        return [_json_ready(item) for item in value.tolist()]
    return value


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare schema/FK statistics across relational DB sources.")
    parser.add_argument(
        "--relbench-stats-json",
        type=Path,
        default=Path("data/statistics/Relbench/schema_graph.json"),
        help="Path to RelBench precomputed schema_graph.json. Use 'none' to skip.",
    )
    parser.add_argument(
        "--existing-root",
        type=Path,
        default=None,
        help="Root containing DBInfer/MTBench datasets with metadata.yaml.",
    )
    parser.add_argument(
        "--synthetic-root",
        type=Path,
        default=Path("syn_data/outputs/databases/syn_v1"),
        help="Root containing synthetic DB directories with schema/schema.json.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("syn_data/outputs/analysis/schema_stats"),
        help="Directory for summary.md, CSV files, and report.json.",
    )
    parser.add_argument("--skip-fanout", action="store_true", help="Skip reading table data for fanout metrics.")
    parser.add_argument("--max-dbs", type=int, default=None, help="Optional per-source database limit for smoke runs.")
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> None:
    args = parse_args(argv)
    relbench_path = args.relbench_stats_json
    if str(relbench_path).lower() in {"none", "null", "-"}:
        relbench_path = None
    report = analyze_sources(
        relbench_stats_json=relbench_path,
        existing_root=args.existing_root,
        synthetic_root=args.synthetic_root,
        output_dir=args.output_dir,
        skip_fanout=bool(args.skip_fanout),
        max_dbs=args.max_dbs,
    )
    print(json.dumps(_json_ready(report), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main(sys.argv[1:])
